name: 'Container health and smoke check'
description: 'Waits for a container, performs a health check and simple smoke test, shows logs on failure, and cleans up the container.'

inputs:
  container-name:
    description: 'Docker container name to check (and clean up)'
    required: true

  port:
    description: 'Port that the container exposes the health endpoint on'
    required: false
    default: '3000'

  health-path:
    description: 'Path to the health endpoint inside the container'
    required: false
    default: '/health'

  max-retries:
    description: 'Maximum number of health check retries'
    required: false
    default: '30'

  retry-delay-seconds:
    description: 'Delay in seconds between health check retries'
    required: false
    default: '2'

runs:
  using: 'composite'
  steps:
    - name: Wait for container to start
      shell: bash
      run: |
        echo "Waiting 10 seconds for container '${{ inputs.container-name }}' to start..."
        sleep 10

    - name: Check for bootloop
      shell: bash
      run: |
        echo "Checking for bootloop on container '${{ inputs.container-name }}'..."

        # Get initial restart count
        INITIAL_RESTARTS=$(docker inspect --format='{{.RestartCount}}' "${{ inputs.container-name }}" 2>/dev/null || echo "0")
        echo "Initial restart count: $INITIAL_RESTARTS"

        # Wait a bit to see if container restarts
        sleep 5

        # Check if container is still running
        if ! docker ps --filter "name=${{ inputs.container-name }}" --format "{{.Names}}" | grep -q "${{ inputs.container-name }}"; then
          echo "❌ Container '${{ inputs.container-name }}' is not running - possible crash or bootloop"
          docker logs "${{ inputs.container-name }}" || true
          exit 1
        fi

        # Get current restart count
        CURRENT_RESTARTS=$(docker inspect --format='{{.RestartCount}}' "${{ inputs.container-name }}" 2>/dev/null || echo "0")
        echo "Current restart count: $CURRENT_RESTARTS"

        # Check if restart count increased
        if [ "$CURRENT_RESTARTS" -gt "$INITIAL_RESTARTS" ]; then
          echo "❌ Container '${{ inputs.container-name }}' restarted during check - bootloop detected"
          docker logs "${{ inputs.container-name }}" || true
          exit 1
        fi

        echo "✅ No bootloop detected for container '${{ inputs.container-name }}'"

    - name: Health check
      shell: bash
      run: |
        HEALTH_URL="http://127.0.0.1:${{ inputs.port }}${{ inputs.health-path }}"
        MAX_RETRIES=${{ inputs.max-retries }}
        RETRY_DELAY=${{ inputs.retry-delay-seconds }}

        echo "Checking health of container '${{ inputs.container-name }}' at ${HEALTH_URL}..."

        RETRY_COUNT=0
        until docker exec "${{ inputs.container-name }}" curl -f "$HEALTH_URL" || [ "$RETRY_COUNT" -eq "$MAX_RETRIES" ]; do
          # Check if container is still running during health checks
          if ! docker ps --filter "name=${{ inputs.container-name }}" --format "{{.Names}}" | grep -q "${{ inputs.container-name }}"; then
            echo "❌ Container '${{ inputs.container-name }}' stopped during health check"
            docker logs "${{ inputs.container-name }}" || true
            exit 1
          fi

          echo "Waiting for health check... ($RETRY_COUNT/$MAX_RETRIES)"
          RETRY_COUNT=$((RETRY_COUNT + 1))
          sleep "$RETRY_DELAY"
        done

        if [ "$RETRY_COUNT" -eq "$MAX_RETRIES" ]; then
          echo "❌ Health check failed for container '${{ inputs.container-name }}'"
          docker logs "${{ inputs.container-name }}" || true
          exit 1
        fi

        echo "✅ Health check passed for container '${{ inputs.container-name }}'"

    - name: Smoke test
      shell: bash
      run: |
        HEALTH_URL="http://127.0.0.1:${{ inputs.port }}${{ inputs.health-path }}"
        echo "Running smoke test against ${HEALTH_URL} for container '${{ inputs.container-name }}'..."

        RESPONSE=$(docker exec "${{ inputs.container-name }}" curl -s "$HEALTH_URL")
        echo "Response: $RESPONSE"

        if echo "$RESPONSE" | grep -q "ok\|healthy\|UP"; then
          echo "✅ Smoke test passed for container '${{ inputs.container-name }}'"
        else
          echo "❌ Smoke test failed for container '${{ inputs.container-name }}'"
          exit 1
        fi

    - name: Final bootloop check
      shell: bash
      run: |
        echo "Performing final bootloop check for container '${{ inputs.container-name }}'..."

        # Get restart count after all checks
        FINAL_RESTARTS=$(docker inspect --format='{{.RestartCount}}' "${{ inputs.container-name }}" 2>/dev/null || echo "0")
        echo "Final restart count: $FINAL_RESTARTS"

        # Ensure container is still running
        if ! docker ps --filter "name=${{ inputs.container-name }}" --format "{{.Names}}" | grep -q "${{ inputs.container-name }}"; then
          echo "❌ Container '${{ inputs.container-name }}' is not running after tests"
          docker logs "${{ inputs.container-name }}" || true
          exit 1
        fi

        # Check if any restarts occurred
        if [ "$FINAL_RESTARTS" -gt "0" ]; then
          echo "⚠️  Warning: Container '${{ inputs.container-name }}' has restarted $FINAL_RESTARTS time(s)"
          docker logs "${{ inputs.container-name }}" || true
          exit 1
        fi

        echo "✅ Container '${{ inputs.container-name }}' is stable with no restarts"

    - name: Show logs on failure
      if: failure()
      shell: bash
      run: |
        echo "Showing logs for failed container '${{ inputs.container-name }}'..."
        docker logs "${{ inputs.container-name }}" || true

    - name: Cleanup container
      if: always()
      shell: bash
      run: |
        echo "Cleaning up container '${{ inputs.container-name }}'..."
        docker rm -f "${{ inputs.container-name }}" || true

