# Optimized Path-based Filters for Container Builds
# This file separates source code changes from test-only changes for efficient CI/CD

# =============================================================================
# SOURCE CODE FILTERS - Trigger builds and deployments
# =============================================================================

# Shared package source changes - affects ALL containers
shared-src:
  - 'containers/shared/src/**'
  - 'containers/shared/lib/**'
  - 'containers/shared/package.json'
  - 'containers/shared/package-lock.json'
  - 'containers/shared/tsconfig.json'
  - 'containers/shared/Dockerfile*'
  - 'containers/shared/.dockerignore'
  - '!containers/shared/**/*.test.*'
  - '!containers/shared/**/__tests__/**'
  - '!containers/shared/**/tests/**'
  - '!containers/shared/**/*.md'
  - '!containers/shared/docs/**'

# Individual container source code filters
bunkbot-src:
  - 'containers/bunkbot/src/**'
  - 'containers/bunkbot/lib/**'
  - 'containers/bunkbot/package.json'
  - 'containers/bunkbot/package-lock.json'
  - 'containers/bunkbot/tsconfig.json'
  - 'containers/bunkbot/Dockerfile*'
  - 'containers/bunkbot/.dockerignore'
  - '!containers/bunkbot/**/*.test.*'
  - '!containers/bunkbot/**/__tests__/**'
  - '!containers/bunkbot/**/tests/**'
  - '!containers/bunkbot/**/*.md'

djcova-src:
  - 'containers/djcova/src/**'
  - 'containers/djcova/lib/**'
  - 'containers/djcova/package.json'
  - 'containers/djcova/package-lock.json'
  - 'containers/djcova/tsconfig.json'
  - 'containers/djcova/Dockerfile*'
  - 'containers/djcova/.dockerignore'
  - '!containers/djcova/**/*.test.*'
  - '!containers/djcova/**/__tests__/**'
  - '!containers/djcova/**/tests/**'
  - '!containers/djcova/**/*.md'

starbunk-dnd-src:
  - 'containers/starbunk-dnd/src/**'
  - 'containers/starbunk-dnd/lib/**'
  - 'containers/starbunk-dnd/package.json'
  - 'containers/starbunk-dnd/package-lock.json'
  - 'containers/starbunk-dnd/tsconfig.json'
  - 'containers/starbunk-dnd/Dockerfile*'
  - 'containers/starbunk-dnd/.dockerignore'
  - '!containers/starbunk-dnd/**/*.test.*'
  - '!containers/starbunk-dnd/**/__tests__/**'
  - '!containers/starbunk-dnd/**/tests/**'
  - '!containers/starbunk-dnd/**/*.md'

covabot-src:
  - 'containers/covabot/src/**'
  - 'containers/covabot/lib/**'
  - 'containers/covabot/package.json'
  - 'containers/covabot/package-lock.json'
  - 'containers/covabot/tsconfig.json'
  - 'containers/covabot/Dockerfile*'
  - 'containers/covabot/.dockerignore'
  - '!containers/covabot/**/*.test.*'
  - '!containers/covabot/**/__tests__/**'
  - '!containers/covabot/**/tests/**'
  - '!containers/covabot/**/*.md'


# =============================================================================
# CONTAINER BUILD DEPENDENCY MATRIX - Optimized for selective rebuilds
# =============================================================================

# Each container needs rebuilding when:
# 1. Its own source code changes
# 2. Shared package source changes
# 3. Critical infrastructure changes

bunkbot:
  - 'containers/bunkbot/src/**'
  - 'containers/bunkbot/lib/**'
  - 'containers/bunkbot/package.json'
  - 'containers/bunkbot/Dockerfile*'
  - 'containers/shared/src/**'
  - 'containers/shared/lib/**'
  - 'containers/shared/package.json'
  - 'docker-compose*.yml'
  - 'package.json'
  - 'tsconfig.json'
  - '!**/*.test.*'
  - '!**/__tests__/**'
  - '!**/tests/**'
  - '!**/*.md'

djcova:
  - 'containers/djcova/src/**'
  - 'containers/djcova/lib/**'
  - 'containers/djcova/package.json'
  - 'containers/djcova/Dockerfile*'
  - 'containers/shared/src/**'
  - 'containers/shared/lib/**'
  - 'containers/shared/package.json'
  - 'docker-compose*.yml'
  - 'package.json'
  - 'tsconfig.json'
  - '!**/*.test.*'
  - '!**/__tests__/**'
  - '!**/tests/**'
  - '!**/*.md'

starbunk-dnd:
  - 'containers/starbunk-dnd/src/**'
  - 'containers/starbunk-dnd/lib/**'
  - 'containers/starbunk-dnd/package.json'
  - 'containers/starbunk-dnd/Dockerfile*'
  - 'containers/shared/src/**'
  - 'containers/shared/lib/**'
  - 'containers/shared/package.json'
  - 'docker-compose*.yml'
  - 'package.json'
  - 'tsconfig.json'
  - '!**/*.test.*'
  - '!**/__tests__/**'
  - '!**/tests/**'
  - '!**/*.md'

covabot:
  - 'containers/covabot/src/**'
  - 'containers/covabot/lib/**'
  - 'containers/covabot/package.json'
  - 'containers/covabot/Dockerfile*'
  - 'containers/shared/src/**'
  - 'containers/shared/lib/**'
  - 'containers/shared/package.json'
  - 'docker-compose*.yml'
  - 'package.json'
  - 'tsconfig.json'
  - '!**/*.test.*'
  - '!**/__tests__/**'
  - '!**/tests/**'
  - '!**/*.md'


# =============================================================================
# TEST-ONLY FILTERS - Trigger tests but not builds
# =============================================================================

# Test files that should only trigger test runs
tests-only:
  - '**/*.test.ts'
  - '**/*.test.js'
  - '**/*.spec.ts'
  - '**/*.spec.js'
  - '**/__tests__/**'
  - '**/tests/**'
  - 'jest.config.js'
  - 'containers/*/jest.config.js'

# Container-specific test filters
bunkbot-tests:
  - 'containers/bunkbot/**/*.test.*'
  - 'containers/bunkbot/**/__tests__/**'
  - 'containers/bunkbot/**/tests/**'
  - 'containers/bunkbot/jest.config.js'

djcova-tests:
  - 'containers/djcova/**/*.test.*'
  - 'containers/djcova/**/__tests__/**'
  - 'containers/djcova/**/tests/**'
  - 'containers/djcova/jest.config.js'

starbunk-dnd-tests:
  - 'containers/starbunk-dnd/**/*.test.*'
  - 'containers/starbunk-dnd/**/__tests__/**'
  - 'containers/starbunk-dnd/**/tests/**'
  - 'containers/starbunk-dnd/jest.config.js'

covabot-tests:
  - 'containers/covabot/**/*.test.*'
  - 'containers/covabot/**/__tests__/**'
  - 'containers/covabot/**/tests/**'
  - 'containers/covabot/jest.config.js'

shared-tests:
  - 'containers/shared/**/*.test.*'
  - 'containers/shared/**/__tests__/**'
  - 'containers/shared/**/tests/**'
  - 'containers/shared/jest.config.js'

# =============================================================================
# CRITICAL INFRASTRUCTURE - Always triggers full rebuild
# =============================================================================

# Container validation workflows and related infrastructure
container-validation:
  - '.github/workflows/container-startup-validation.yml'
  - '.github/workflows/code-quality-gates.yml'
  - '.github/workflows/build-metrics.yml'
  - '.github/workflows/pr-validation.yml'
  - '.github/path-filters*.yml'

critical-infrastructure:
  - '.github/workflows/**'
  - '.github/actions/**'
  - '.github/path-filters*.yml'
  - 'package.json'
  - 'package-lock.json'
  - 'tsconfig.json'
  - 'docker-compose*.yml'
  - '.eslintrc*'
  - '.prettierrc*'
  - '.nvmrc'
  - '.node-version'
  - 'Dockerfile'
  - '.dockerignore'

# Docker-specific changes
docker-infrastructure:
  - 'docker-compose*.yml'
  - 'Dockerfile*'
  - '.dockerignore'
  - 'containers/*/Dockerfile*'
  - 'containers/*/.dockerignore'

# Root configuration changes
root-config:
  - 'package.json'
  - 'package-lock.json'
  - 'tsconfig.json'
  - '.eslintrc*'
  - '.prettierrc*'
  - 'jest.config.js'
  - '.nvmrc'
  - '.node-version'

# =============================================================================
# DOCUMENTATION AND NON-FUNCTIONAL FILES - Usually no builds needed
# =============================================================================

docs-only:
  - '**/*.md'
  - 'docs/**'
  - '.github/ISSUE_TEMPLATE/**'
  - '.github/PULL_REQUEST_TEMPLATE.md'
  - 'README*'
  - 'CHANGELOG*'
  - 'CONTRIBUTING*'
  - 'LICENSE*'
  - '**/.gitkeep'

# IDE and tooling files that don't affect builds
tooling-only:
  - '.vscode/**'
  - '.idea/**'
  - '**/.DS_Store'
  - '.gitignore'
  - '**/*ignore'

# =============================================================================
# COMPOSITE FILTERS - For advanced workflow orchestration
# =============================================================================

# Any source code change (excluding tests and docs)
any-source-change:
  - 'containers/*/src/**'
  - 'containers/*/lib/**'
  - 'containers/*/package.json'
  - 'package.json'
  - 'tsconfig.json'
  - '!**/*.test.*'
  - '!**/__tests__/**'
  - '!**/tests/**'
  - '!**/*.md'
  - '!docs/**'

# Any infrastructure change requiring full rebuild
any-infrastructure-change:
  - '.github/workflows/**'
  - 'docker-compose*.yml'
  - 'package.json'
  - 'tsconfig.json'
  - '.eslintrc*'
  - 'Dockerfile*'
  - '.dockerignore'

# Dependency changes that might affect multiple containers
dependency-changes:
  - 'package.json'
  - 'package-lock.json'
  - 'containers/shared/package.json'
  - 'containers/shared/package-lock.json'
  - 'containers/*/package.json'
  - 'containers/*/package-lock.json'