# Path-based filters for container builds
# This file centralizes all path filtering logic for CI/CD workflows

# Shared package - affects ALL containers when changed
shared:
  - 'containers/shared/**'
  - '!containers/shared/README.md'
  - '!containers/shared/docs/**'
  - '!containers/shared/**/*.md'

# Individual container filters
bunkbot:
  - 'containers/bunkbot/**'
  - '!containers/bunkbot/README.md'
  - '!containers/bunkbot/docs/**'
  - '!containers/bunkbot/**/*.md'

djcova:
  - 'containers/djcova/**'
  - '!containers/djcova/README.md'
  - '!containers/djcova/docs/**'
  - '!containers/djcova/**/*.md'

starbunk-dnd:
  - 'containers/starbunk-dnd/**'
  - '!containers/starbunk-dnd/README.md'
  - '!containers/starbunk-dnd/docs/**'
  - '!containers/starbunk-dnd/**/*.md'

covabot:
  - 'containers/covabot/**'
  - '!containers/covabot/README.md'
  - '!containers/covabot/docs/**'
  - '!containers/covabot/**/*.md'

# Root-level files that affect all containers
root-files:
  - 'package.json'
  - 'package-lock.json'
  - 'tsconfig.json'
  - '.eslintrc.json'
  - 'jest.config.js'
  - '.nvmrc'
  - '.node-version'
  - 'lerna.json'
  - 'nx.json'

# CI/CD workflow changes
workflows:
  - '.github/workflows/**'
  - '.github/actions/**'
  - '.github/path-filters.yml'

# Docker configuration changes
docker:
  - 'docker-compose*.yml'
  - 'Dockerfile*'
  - '.dockerignore'
  - 'containers/*/Dockerfile'
  - 'containers/*/.dockerignore'

# Security and dependency updates
security:
  - '.github/dependabot.yml'
  - '.github/security.yml'
  - 'package-lock.json'
  - 'containers/*/package-lock.json'
  - '.github/workflows/security.yml'

# Documentation (usually doesn't require builds)
docs:
  - '**/*.md'
  - 'docs/**'
  - '.github/ISSUE_TEMPLATE/**'
  - '.github/PULL_REQUEST_TEMPLATE.md'
  - 'README.md'
  - 'CHANGELOG.md'
  - 'CONTRIBUTING.md'
  - 'LICENSE'

# Test files (may require test runs but not necessarily builds)
tests:
  - '**/*.test.ts'
  - '**/*.test.js'
  - '**/*.spec.ts'
  - '**/*.spec.js'
  - 'containers/*/tests/**'
  - 'containers/shared/tests/**'
  - 'jest.config.js'
  - '**/__tests__/**'

# Configuration files that might affect builds
config:
  - '.eslintrc*'
  - '.prettierrc*'
  - 'tsconfig*.json'
  - 'babel.config.*'
  - 'webpack.config.*'
  - 'vite.config.*'

# Container-specific dependency combinations
# These provide more granular dependency detection for advanced scenarios
# Useful for detecting when a container needs rebuilding due to shared dependencies

bunkbot-deps:
  - 'containers/bunkbot/src/**'
  - 'containers/bunkbot/lib/**'
  - 'containers/bunkbot/package.json'
  - 'containers/bunkbot/package-lock.json'
  - 'containers/bunkbot/Dockerfile'
  - 'containers/shared/src/**'
  - 'containers/shared/lib/**'
  - 'containers/shared/package.json'
  - 'containers/shared/**/*.ts'
  - 'containers/shared/**/*.js'
  - '!**/*.md'
  - '!**/docs/**'
  - '!**/node_modules/**'
  - '!**/dist/**'

djcova-deps:
  - 'containers/djcova/src/**'
  - 'containers/djcova/lib/**'
  - 'containers/djcova/package.json'
  - 'containers/djcova/package-lock.json'
  - 'containers/djcova/Dockerfile'
  - 'containers/shared/src/**'
  - 'containers/shared/lib/**'
  - 'containers/shared/package.json'
  - 'containers/shared/**/*.ts'
  - 'containers/shared/**/*.js'
  - '!**/*.md'
  - '!**/docs/**'
  - '!**/node_modules/**'
  - '!**/dist/**'

starbunk-dnd-deps:
  - 'containers/starbunk-dnd/src/**'
  - 'containers/starbunk-dnd/lib/**'
  - 'containers/starbunk-dnd/package.json'
  - 'containers/starbunk-dnd/package-lock.json'
  - 'containers/starbunk-dnd/Dockerfile'
  - 'containers/shared/src/**'
  - 'containers/shared/lib/**'
  - 'containers/shared/package.json'
  - 'containers/shared/**/*.ts'
  - 'containers/shared/**/*.js'
  - '!**/*.md'
  - '!**/docs/**'
  - '!**/node_modules/**'
  - '!**/dist/**'

covabot-deps:
  - 'containers/covabot/src/**'
  - 'containers/covabot/lib/**'
  - 'containers/covabot/package.json'
  - 'containers/covabot/package-lock.json'
  - 'containers/covabot/Dockerfile'
  - 'containers/shared/src/**'
  - 'containers/shared/lib/**'
  - 'containers/shared/package.json'
  - 'containers/shared/**/*.ts'
  - 'containers/shared/**/*.js'
  - '!**/*.md'
  - '!**/docs/**'
  - '!**/node_modules/**'
  - '!**/dist/**'

# Critical files that always trigger full builds
critical:
  - '.github/workflows/container-build-test-publish.yml'
  - '.github/workflows/pr-checks.yml'
  - '.github/path-filters.yml'
  - 'package.json'
  - 'docker-compose*.yml'

# Files that never trigger builds
ignore:
  - '**/*.md'
  - 'docs/**'
  - '.github/ISSUE_TEMPLATE/**'
  - '.github/PULL_REQUEST_TEMPLATE.md'
  - '**/README.md'
  - '**/CHANGELOG.md'
  - '**/LICENSE'
  - '**/.gitkeep'
  - '**/.gitignore'
  - '**/.*ignore'
