# Path-based filters for container builds
# This file centralizes all path filtering logic for CI/CD workflows

# Shared package - affects ALL containers when changed
# This includes shared code, infrastructure changes, and global configuration
shared:
  - 'containers/shared/**'
  - 'docker-compose*.yml'
  - 'package.json'
  - 'package-lock.json'
  - 'tsconfig.json'
  - '.github/workflows/**'
  - '.github/path-filters.yml'
  - 'Dockerfile*'
  - '.dockerignore'
  - '.eslintrc*'
  - '.prettierrc*'
  - 'jest.config.js'
  - '.nvmrc'
  - '.node-version'
  - '!containers/shared/README.md'
  - '!containers/shared/docs/**'
  - '!containers/shared/**/*.md'
  - '!**/*.test.ts'
  - '!**/*.test.js'
  - '!**/*.spec.ts'
  - '!**/*.spec.js'
  - '!**/__tests__/**'
  - '!**/tests/**'
  - '!**/*.md'
  - '!docs/**'
  - '!.vscode/**'
  - '!.idea/**'
  - '!.github/ISSUE_TEMPLATE/**'

# Individual container filters
# Each container is triggered by:
# 1. Changes to its own directory
# 2. Changes to shared dependencies
# 3. Infrastructure changes (Docker Compose, CI/CD, root configs)
bunkbot:
  - 'containers/bunkbot/**'
  - 'containers/shared/**'
  - 'docker-compose*.yml'
  - 'package.json'
  - 'package-lock.json'
  - 'tsconfig.json'
  - '.github/workflows/**'
  - '.github/path-filters.yml'
  - 'Dockerfile*'
  - '.dockerignore'
  - '!containers/bunkbot/README.md'
  - '!containers/bunkbot/docs/**'
  - '!containers/bunkbot/**/*.md'
  - '!**/*.test.ts'
  - '!**/*.test.js'
  - '!**/*.spec.ts'
  - '!**/*.spec.js'
  - '!**/__tests__/**'
  - '!**/tests/**'
  - '!.vscode/**'
  - '!.idea/**'

djcova:
  - 'containers/djcova/**'
  - 'containers/shared/**'
  - 'docker-compose*.yml'
  - 'package.json'
  - 'package-lock.json'
  - 'tsconfig.json'
  - '.github/workflows/**'
  - '.github/path-filters.yml'
  - 'Dockerfile*'
  - '.dockerignore'
  - '!containers/djcova/README.md'
  - '!containers/djcova/docs/**'
  - '!containers/djcova/**/*.md'
  - '!**/*.test.ts'
  - '!**/*.test.js'
  - '!**/*.spec.ts'
  - '!**/*.spec.js'
  - '!**/__tests__/**'
  - '!**/tests/**'
  - '!.vscode/**'
  - '!.idea/**'

starbunk-dnd:
  - 'containers/starbunk-dnd/**'
  - 'containers/shared/**'
  - 'docker-compose*.yml'
  - 'package.json'
  - 'package-lock.json'
  - 'tsconfig.json'
  - '.github/workflows/**'
  - '.github/path-filters.yml'
  - 'Dockerfile*'
  - '.dockerignore'
  - '!containers/starbunk-dnd/README.md'
  - '!containers/starbunk-dnd/docs/**'
  - '!containers/starbunk-dnd/**/*.md'
  - '!**/*.test.ts'
  - '!**/*.test.js'
  - '!**/*.spec.ts'
  - '!**/*.spec.js'
  - '!**/__tests__/**'
  - '!**/tests/**'
  - '!.vscode/**'
  - '!.idea/**'

snowbunk:
  - 'containers/snowbunk/**'
  - 'containers/shared/**'
  - 'docker-compose*.yml'
  - 'package.json'
  - 'package-lock.json'
  - 'tsconfig.json'
  - '.github/workflows/**'
  - '.github/path-filters.yml'
  - 'Dockerfile*'
  - '.dockerignore'
  - '!containers/snowbunk/README.md'
  - '!containers/snowbunk/docs/**'
  - '!containers/snowbunk/**/*.md'
  - '!**/*.test.ts'
  - '!**/*.test.js'
  - '!**/*.spec.ts'
  - '!**/*.spec.js'
  - '!**/__tests__/**'
  - '!**/tests/**'
  - '!.vscode/**'
  - '!.idea/**'

covabot:
  - 'containers/covabot/**'
  - 'containers/shared/**'
  - 'docker-compose*.yml'
  - 'package.json'
  - 'package-lock.json'
  - 'tsconfig.json'
  - '.github/workflows/**'
  - '.github/path-filters.yml'
  - 'Dockerfile*'
  - '.dockerignore'
  - '!containers/covabot/README.md'
  - '!containers/covabot/docs/**'
  - '!containers/covabot/**/*.md'
  - '!**/*.test.ts'
  - '!**/*.test.js'
  - '!**/*.spec.ts'
  - '!**/*.spec.js'
  - '!**/__tests__/**'
  - '!**/tests/**'
  - '!.vscode/**'
  - '!.idea/**'

# Root-level files that affect all containers
root-files:
  - 'package.json'
  - 'package-lock.json'
  - 'tsconfig.json'
  - '.eslintrc.json'
  - 'jest.config.js'
  - '.nvmrc'
  - '.node-version'
  - 'lerna.json'
  - 'nx.json'

# CI/CD workflow changes
workflows:
  - '.github/workflows/**'
  - '.github/actions/**'
  - '.github/path-filters.yml'

# Docker configuration changes - affects ALL containers
docker:
  - 'docker-compose*.yml'
  - 'docker-compose.snapshot.yml'
  - 'docker-compose.latest.yml'
  - 'Dockerfile*'
  - '.dockerignore'
  - 'containers/*/Dockerfile'
  - 'containers/*/.dockerignore'
  - 'containers/shared/Dockerfile'
  - '.github/workflows/container-*.yml'
  - '.github/workflows/docker-*.yml'

# Security and dependency updates
security:
  - '.github/dependabot.yml'
  - '.github/security.yml'
  - 'package-lock.json'
  - 'containers/*/package-lock.json'
  - '.github/workflows/security.yml'

# Documentation (usually doesn't require builds)
docs:
  - '**/*.md'
  - 'docs/**'
  - '.github/ISSUE_TEMPLATE/**'
  - '.github/PULL_REQUEST_TEMPLATE.md'
  - 'README.md'
  - 'CHANGELOG.md'
  - 'CONTRIBUTING.md'
  - 'LICENSE'

# Test files (may require test runs but not necessarily builds)
tests:
  - '**/*.test.ts'
  - '**/*.test.js'
  - '**/*.spec.ts'
  - '**/*.spec.js'
  - 'containers/*/tests/**'
  - 'containers/shared/tests/**'
  - 'jest.config.js'
  - '**/__tests__/**'

# Configuration files that might affect builds
config:
  - '.eslintrc*'
  - '.prettierrc*'
  - 'tsconfig*.json'
  - 'babel.config.*'
  - 'webpack.config.*'
  - 'vite.config.*'

# Container-specific dependency combinations
# These provide more granular dependency detection for advanced scenarios
# Useful for detecting when a container needs rebuilding due to shared dependencies

bunkbot-deps:
  - 'containers/bunkbot/src/**'
  - 'containers/bunkbot/lib/**'
  - 'containers/bunkbot/package.json'
  - 'containers/bunkbot/package-lock.json'
  - 'containers/bunkbot/Dockerfile'
  - 'containers/bunkbot/.dockerignore'
  - 'containers/shared/src/**'
  - 'containers/shared/lib/**'
  - 'containers/shared/package.json'
  - 'containers/shared/**/*.ts'
  - 'containers/shared/**/*.js'
  - 'docker-compose*.yml'
  - 'package.json'
  - 'package-lock.json'
  - 'tsconfig.json'
  - '.github/workflows/**'
  - '!**/*.md'
  - '!**/docs/**'
  - '!**/node_modules/**'
  - '!**/dist/**'
  - '!**/*.test.ts'
  - '!**/*.test.js'
  - '!**/*.spec.ts'
  - '!**/*.spec.js'
  - '!**/__tests__/**'
  - '!**/tests/**'

djcova-deps:
  - 'containers/djcova/src/**'
  - 'containers/djcova/lib/**'
  - 'containers/djcova/package.json'
  - 'containers/djcova/package-lock.json'
  - 'containers/djcova/Dockerfile'
  - 'containers/djcova/.dockerignore'
  - 'containers/shared/src/**'
  - 'containers/shared/lib/**'
  - 'containers/shared/package.json'
  - 'containers/shared/**/*.ts'
  - 'containers/shared/**/*.js'
  - 'docker-compose*.yml'
  - 'package.json'
  - 'package-lock.json'
  - 'tsconfig.json'
  - '.github/workflows/**'
  - '!**/*.md'
  - '!**/docs/**'
  - '!**/node_modules/**'
  - '!**/dist/**'
  - '!**/*.test.ts'
  - '!**/*.test.js'
  - '!**/*.spec.ts'
  - '!**/*.spec.js'
  - '!**/__tests__/**'
  - '!**/tests/**'

starbunk-dnd-deps:
  - 'containers/starbunk-dnd/src/**'
  - 'containers/starbunk-dnd/lib/**'
  - 'containers/starbunk-dnd/package.json'
  - 'containers/starbunk-dnd/package-lock.json'
  - 'containers/starbunk-dnd/Dockerfile'
  - 'containers/starbunk-dnd/.dockerignore'
  - 'containers/shared/src/**'
  - 'containers/shared/lib/**'
  - 'containers/shared/package.json'
  - 'containers/shared/**/*.ts'
  - 'containers/shared/**/*.js'
  - 'docker-compose*.yml'
  - 'package.json'
  - 'package-lock.json'
  - 'tsconfig.json'
  - '.github/workflows/**'
  - '!**/*.md'
  - '!**/docs/**'
  - '!**/node_modules/**'
  - '!**/dist/**'
  - '!**/*.test.ts'
  - '!**/*.test.js'
  - '!**/*.spec.ts'
  - '!**/*.spec.js'
  - '!**/__tests__/**'
  - '!**/tests/**'

snowbunk-deps:
  - 'containers/snowbunk/src/**'
  - 'containers/snowbunk/lib/**'
  - 'containers/snowbunk/package.json'
  - 'containers/snowbunk/package-lock.json'
  - 'containers/snowbunk/Dockerfile'
  - 'containers/snowbunk/.dockerignore'
  - 'containers/shared/src/**'
  - 'containers/shared/lib/**'
  - 'containers/shared/package.json'
  - 'containers/shared/**/*.ts'
  - 'containers/shared/**/*.js'
  - 'docker-compose*.yml'
  - 'package.json'
  - 'package-lock.json'
  - 'tsconfig.json'
  - '.github/workflows/**'
  - '!**/*.md'
  - '!**/docs/**'
  - '!**/node_modules/**'
  - '!**/dist/**'
  - '!**/*.test.ts'
  - '!**/*.test.js'
  - '!**/*.spec.ts'
  - '!**/*.spec.js'
  - '!**/__tests__/**'
  - '!**/tests/**'

covabot-deps:
  - 'containers/covabot/src/**'
  - 'containers/covabot/lib/**'
  - 'containers/covabot/package.json'
  - 'containers/covabot/package-lock.json'
  - 'containers/covabot/Dockerfile'
  - 'containers/covabot/.dockerignore'
  - 'containers/shared/src/**'
  - 'containers/shared/lib/**'
  - 'containers/shared/package.json'
  - 'containers/shared/**/*.ts'
  - 'containers/shared/**/*.js'
  - 'docker-compose*.yml'
  - 'package.json'
  - 'package-lock.json'
  - 'tsconfig.json'
  - '.github/workflows/**'
  - '!**/*.md'
  - '!**/docs/**'
  - '!**/node_modules/**'
  - '!**/dist/**'
  - '!**/*.test.ts'
  - '!**/*.test.js'
  - '!**/*.spec.ts'
  - '!**/*.spec.js'
  - '!**/__tests__/**'
  - '!**/tests/**'

# Critical files that always trigger full builds for ALL containers
critical:
  - '.github/workflows/container-build-test-publish.yml'
  - '.github/workflows/pr-checks.yml'
  - '.github/workflows/main-deploy.yml'
  - '.github/workflows/docker-build-reusable.yml'
  - '.github/workflows/manual-docker-build.yml'
  - '.github/path-filters.yml'
  - 'package.json'
  - 'package-lock.json'
  - 'docker-compose*.yml'
  - 'docker-compose.snapshot.yml'
  - 'docker-compose.latest.yml'
  - 'tsconfig.json'
  - 'containers/shared/package.json'
  - 'Dockerfile'
  - '.dockerignore'

# Files that never trigger builds
ignore:
  - '**/*.md'
  - 'docs/**'
  - '.github/ISSUE_TEMPLATE/**'
  - '.github/PULL_REQUEST_TEMPLATE.md'
  - '**/README.md'
  - '**/CHANGELOG.md'
  - '**/LICENSE'
  - '**/.gitkeep'
  - '**/.gitignore'
  - '**/.*ignore'
  - '**/*.test.ts'
  - '**/*.test.js'
  - '**/*.spec.ts'
  - '**/*.spec.js'
  - '**/__tests__/**'
  - '**/tests/**'
  - '.vscode/**'
  - '.idea/**'
  - '**/.DS_Store'
  - '**/node_modules/**'
  - '**/dist/**'
  - '**/build/**'
  - '**/coverage/**'
  - '**/.nyc_output/**'
  - '**/logs/**'
  - '**/*.log'
