# Code Rabbit Configuration for Starbunk Discord Bot Project
# Optimized for TypeScript/Node.js containerized architecture

# Review settings
reviews:
  # Enable high-quality reviews with focus on security and performance
  high_level_summary: true
  poem: true
  review_status: true

  # Path-based review assignments
  path_instructions:
    - path: "containers/shared/**"
      instructions: |
        Shared utilities and services library - Focus on:
        - Breaking changes that affect all containers
        - Performance implications for shared services
        - Type safety and API consistency
        - Memory leaks in shared utilities
        - Security vulnerabilities in shared code

    - path: "containers/bunkbot/**"
      instructions: |
        Discord bot with listener, webhook, identity, guild functionality - Focus on:
        - Discord.js best practices and rate limiting
        - Guild-specific message handling and filtering
        - Webhook integrations and error handling
        - Identity service usage and validation
        - Error handling for Discord API failures

    - path: "containers/djcova/**"
      instructions: |
        Server-agnostic music bot with no identity requirements - Focus on:
        - Audio streaming performance and memory usage
        - YouTube-dl integration and FFmpeg processing
        - Voice connection management and cleanup
        - Queue management and concurrent access
        - Memory usage optimization for audio processing

    - path: "containers/covabot/**"
      instructions: |
        Discord bot with listener, identity, LLM integration, AI functionality - Focus on:
        - LLM integration security and rate limiting
        - Identity management and server/channel restrictions
        - Conversation memory handling and persistence
        - Vector database query optimization
        - AI service error handling and fallbacks

    - path: "containers/starbunk-dnd/**"
      instructions: |
        D&D bot with game mechanics and rule engine functionality - Focus on:
        - D&D rule engine accuracy and performance
        - Game state management and persistence
        - User input validation and sanitization
        - Dice rolling and probability calculations
        - Character sheet and campaign data handling

    - path: "containers/snowbunk/**"
      instructions: |
        Production-only message bridge for two specific guilds with identity - Focus on:
        - Production deployment considerations and stability
        - Identity verification and guild-specific logic
        - Message synchronization between guilds
        - Cross-guild bridging error handling
        - Resource optimization for production workloads

    - path: ".github/workflows/**"
      instructions: |
        Focus on:
        - CI/CD security and secret handling
        - Resource optimization and cost efficiency
        - Workflow reliability and error handling
        - Container build optimization
        - Path-based conditional logic correctness

    - path: "containers/*/package.json"
      instructions: |
        Focus on:
        - Dependency security vulnerabilities
        - Version compatibility issues
        - Unnecessary dependencies
        - License compatibility

    - path: "docker-compose*.yml"
      instructions: |
        Focus on:
        - Container security configurations
        - Resource limits and health checks
        - Network security and isolation
        - Volume mount security
        - Environment variable handling
