services:
    bunkbot-dev:
        build:
            context: .
            dockerfile: Dockerfile.dev
        container_name: bunkbot-dev
        ports:
            - '3000:3000'
        env_file: .env
        command: npm run dev

volumes:
    node_modules:
