services:
    bunkbot-dev:
        build:
            context: .
            dockerfile: Dockerfile
            # Add build cache to speed up rebuilds
            cache_from:
                - node:18-alpine
        container_name: bunkbot-dev
        ports:
            - '3000:3000'
        env_file: .env
        command: npm run dev
        # Use consistent named volumes for node_modules
        volumes:
            - ./:/app:delegated
            - node_modules:/app/node_modules
        # Enable Node.js optimizations
        environment:
            - NODE_ENV=development
            - NODE_OPTIONS=--max-old-space-size=2048

volumes:
    node_modules:
