services:
  bunkbot-ts:
    environment:
      # Include explicit environment variables for development
      # These will override values from .env
      - NODE_ENV=development
      # If the .env file is missing variables, these defaults help with debugging
      - STARBUNK_TOKEN=${STARBUNK_TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - GUILD_ID=${GUILD_ID}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      # Mount source code for live development
      - ./src:/app/src:delegated
      # Mount .env file directly to ensure it's available
      - ./.env:/app/.env:ro
    # In development, you can use dev mode for hot reloading
    command: npm run dev
