version: '3.8'
services:
    bunkbot-dev:
        build:
            context: .
            dockerfile: Dockerfile.dev
        container_name: bunkbot-dev
        volumes:
            - .:/app
            - /app/node_modules
        ports:
            - '3000:3000'
        env_file: .env
        command: yarn dev
