# Docker Compose for Production Deployment (Latest Images)
# ========================================================
# This file is designed for production deployment using the latest stable images.
#
# Prerequisites:
#   - Ensure .env file exists in the same directory as this compose file
#   - All required environment variables must be defined in .env file
#   - Verify all latest images are available in GHCR
#
# Usage:
#   docker-compose -f docker-compose.latest.yml up -d
#
# Image Format: ghcr.io/andrewgari/{service}:latest
# Example: ghcr.io/andrewgari/bunkbot:latest

version: '3.8'

services:
  # BunkBot - Reply bots and admin commands (Latest Stable)
  bunkbot:
    image: ghcr.io/andrewgari/bunkbot:latest
    container_name: starbunk-bunkbot-latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - STARBUNK_TOKEN=${STARBUNK_TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - GUILD_ID=${GUILD_ID}
      - WEBHOOK_URL=${WEBHOOK_URL:-}
      - DATABASE_URL=${DATABASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - OPENAI_DEFAULT_MODEL=${OPENAI_DEFAULT_MODEL:-gpt-4o-mini}
      - DEBUG_MODE=${DEBUG_MODE:-false}
      - TESTING_SERVER_IDS=${TESTING_SERVER_IDS:-}
      - TESTING_CHANNEL_IDS=${TESTING_CHANNEL_IDS:-}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - starbunk-latest-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # DJCova - Music service (Latest Stable)
  djcova:
    image: ghcr.io/andrewgari/djcova:latest
    container_name: starbunk-djcova-latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - STARBUNK_TOKEN=${STARBUNK_TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - GUILD_ID=${GUILD_ID}
      - DEBUG_MODE=${DEBUG_MODE:-false}
      - TESTING_SERVER_IDS=${TESTING_SERVER_IDS:-}
      - TESTING_CHANNEL_IDS=${TESTING_CHANNEL_IDS:-}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    volumes:
      # Unraid-compatible host path mounts for latest/production
      - ${UNRAID_APPDATA_PATH:-./data}/djcova:/app/cache
      - ${UNRAID_APPDATA_PATH:-./data}/djcova/temp:/tmp
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3001/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - starbunk-latest-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # Starbunk-DND - D&D features and bridge (Latest Stable)
  starbunk-dnd:
    image: ghcr.io/andrewgari/starbunk-dnd:latest
    container_name: starbunk-dnd-latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - STARBUNK_TOKEN=${STARBUNK_TOKEN}
      - SNOWBUNK_TOKEN=${SNOWBUNK_TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - GUILD_ID=${GUILD_ID}
      - DATABASE_URL=${DATABASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_DEFAULT_MODEL=${OPENAI_DEFAULT_MODEL:-gpt-4o-mini}
      - OLLAMA_API_URL=${OLLAMA_API_URL:-}
      - OLLAMA_DEFAULT_MODEL=${OLLAMA_DEFAULT_MODEL:-}
      - DEBUG_MODE=${DEBUG_MODE:-false}
      - TESTING_SERVER_IDS=${TESTING_SERVER_IDS:-}
      - TESTING_CHANNEL_IDS=${TESTING_CHANNEL_IDS:-}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    volumes:
      # Unraid-compatible host path mounts for latest/production
      - ${UNRAID_APPDATA_PATH:-./data}/starbunk-dnd/data:/app/data
      - ${UNRAID_APPDATA_PATH:-./data}/starbunk-dnd/campaigns:/app/data/campaigns
      - ${UNRAID_APPDATA_PATH:-./data}/starbunk-dnd/context:/app/data/llm_context
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3002/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - starbunk-latest-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # CovaBot - AI personality bot (Latest Stable)
  covabot:
    image: ghcr.io/andrewgari/covabot:latest
    container_name: starbunk-covabot-latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - STARBUNK_TOKEN=${STARBUNK_TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - GUILD_ID=${GUILD_ID}
      - DATABASE_URL=${DATABASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_DEFAULT_MODEL=${OPENAI_DEFAULT_MODEL:-gpt-4o-mini}
      - DEBUG_MODE=${DEBUG_MODE:-false}
      - TESTING_SERVER_IDS=${TESTING_SERVER_IDS:-}
      - TESTING_CHANNEL_IDS=${TESTING_CHANNEL_IDS:-}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      # CovaBot-specific configuration
      - USE_DATABASE=${USE_DATABASE:-false}
      - COVABOT_DATA_DIR=/app/data
      - COVABOT_API_KEY=${COVABOT_API_KEY:-}
    volumes:
      # Unraid-compatible host path mount for CovaBot personality notes (latest/production)
      - ${UNRAID_APPDATA_PATH:-./data}/covabot:/app/data
    ports:
      # Expose web interface for personality management (latest/production)
      - "${COVABOT_WEB_PORT:-3001}:3001"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3001/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - starbunk-latest-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

# Note: Using host path mounts for Unraid compatibility
# Latest/production data persists in ${UNRAID_APPDATA_PATH:-./data}/ directories
# Default fallback to ./data/ for non-Unraid environments

# Custom network for service communication (latest/production)
networks:
  starbunk-latest-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16
