# Docker Compose for PR Snapshot Testing
# =====================================
# This file is designed for testing PR snapshot images with predictable naming.
# 
# Usage:
#   1. Set the PR_NUMBER environment variable:
#      export PR_NUMBER=123
#   2. Run with: docker-compose -f docker-compose.snapshot.yml up
#   3. Or specify PR inline: PR_NUMBER=123 docker-compose -f docker-compose.snapshot.yml up
#
# Image Format: ghcr.io/andrewgari/starbunk/{service}:pr-{number}-snapshot
# Example: ghcr.io/andrewgari/starbunk/bunkbot:pr-123-snapshot
version: '3.8'

services:
  # PostgreSQL Database - Shared by services that need persistence
  postgres:
    image: postgres:15-alpine
    container_name: starbunk-postgres-snapshot
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-starbunk}
      POSTGRES_USER: ${POSTGRES_USER:-starbunk}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_snapshot_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d:ro
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-starbunk} -d ${POSTGRES_DB:-starbunk}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - starbunk-snapshot-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # BunkBot - Reply bots and admin commands (PR Snapshot)
  bunkbot:
    image: ghcr.io/andrewgari/starbunk/bunkbot:pr-${PR_NUMBER:-CHANGE_ME}-snapshot
    container_name: starbunk-bunkbot-snapshot
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - STARBUNK_TOKEN=${STARBUNK_TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - GUILD_ID=${GUILD_ID}
      - WEBHOOK_URL=${WEBHOOK_URL:-}
      - DATABASE_URL=${DATABASE_URL:-postgresql://${POSTGRES_USER:-starbunk}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-starbunk}}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - OPENAI_DEFAULT_MODEL=${OPENAI_DEFAULT_MODEL:-gpt-4o-mini}
      - DEBUG_MODE=${DEBUG_MODE:-true}
      - LOG_LEVEL=${LOG_LEVEL:-debug}
    ports:
      - "${BUNKBOT_PORT:-3000}:3000"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - starbunk-snapshot-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # DJCova - Music service (PR Snapshot)
  djcova:
    image: ghcr.io/andrewgari/starbunk/djcova:pr-${PR_NUMBER:-CHANGE_ME}-snapshot
    container_name: starbunk-djcova-snapshot
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - STARBUNK_TOKEN=${STARBUNK_TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - GUILD_ID=${GUILD_ID}
      - DEBUG_MODE=${DEBUG_MODE:-true}
      - LOG_LEVEL=${LOG_LEVEL:-debug}
    ports:
      - "${DJCOVA_PORT:-3001}:3001"
    volumes:
      - djcova_snapshot_cache:/app/cache
      - djcova_snapshot_temp:/tmp
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3001/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - starbunk-snapshot-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # Starbunk-DND - D&D features and bridge (PR Snapshot)
  starbunk-dnd:
    image: ghcr.io/andrewgari/starbunk/starbunk-dnd:pr-${PR_NUMBER:-CHANGE_ME}-snapshot
    container_name: starbunk-dnd-snapshot
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - STARBUNK_TOKEN=${STARBUNK_TOKEN}
      - SNOWBUNK_TOKEN=${SNOWBUNK_TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - GUILD_ID=${GUILD_ID}
      - DATABASE_URL=${DATABASE_URL:-postgresql://${POSTGRES_USER:-starbunk}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-starbunk}}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_DEFAULT_MODEL=${OPENAI_DEFAULT_MODEL:-gpt-4o-mini}
      - OLLAMA_API_URL=${OLLAMA_API_URL:-}
      - OLLAMA_DEFAULT_MODEL=${OLLAMA_DEFAULT_MODEL:-}
      - DEBUG_MODE=${DEBUG_MODE:-true}
      - LOG_LEVEL=${LOG_LEVEL:-debug}
    ports:
      - "${STARBUNK_DND_PORT:-3002}:3002"
    volumes:
      - dnd_snapshot_data:/app/data
      - dnd_snapshot_campaigns:/app/data/campaigns
      - dnd_snapshot_context:/app/data/llm_context
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3002/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - starbunk-snapshot-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # CovaBot - AI personality bot (PR Snapshot)
  covabot:
    image: ghcr.io/andrewgari/starbunk/covabot:pr-${PR_NUMBER:-CHANGE_ME}-snapshot
    container_name: starbunk-covabot-snapshot
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - STARBUNK_TOKEN=${STARBUNK_TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - GUILD_ID=${GUILD_ID}
      - DATABASE_URL=${DATABASE_URL:-postgresql://${POSTGRES_USER:-starbunk}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-starbunk}}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_DEFAULT_MODEL=${OPENAI_DEFAULT_MODEL:-gpt-4o-mini}
      - DEBUG_MODE=${DEBUG_MODE:-true}
      - LOG_LEVEL=${LOG_LEVEL:-debug}
    ports:
      - "${COVABOT_PORT:-3003}:3003"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3003/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - starbunk-snapshot-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

# Named volumes for persistent data (snapshot-specific)
volumes:
  postgres_snapshot_data:
    driver: local
  djcova_snapshot_cache:
    driver: local
  djcova_snapshot_temp:
    driver: local
  dnd_snapshot_data:
    driver: local
  dnd_snapshot_campaigns:
    driver: local
  dnd_snapshot_context:
    driver: local

# Custom network for service communication (snapshot-specific)
networks:
  starbunk-snapshot-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
