version: '3.8'
services:
    cypress:
        build:
            context: .
            dockerfile: Dockerfile.cypress
            # Use BuildKit for faster builds
            args:
                BUILDKIT_INLINE_CACHE: 1
        container_name: starbunk-cypress
        volumes:
            # Mount only necessary directories
            - ./cypress/screenshots:/app/cypress/screenshots
            - ./cypress/videos:/app/cypress/videos
            - ./cypress/downloads:/app/cypress/downloads
            - ./cypress/fixtures:/app/cypress/fixtures
            # Use named volume for node_modules to avoid overwriting with local node_modules
            - cypress_node_modules:/app/node_modules
        environment:
            - CYPRESS_baseUrl=http://localhost:3000
            - NODE_ENV=test
            - CYPRESS_FORCE_MINIMAL_BROWSER=true
            - CYPRESS_BROWSER_ARGS=--disable-gpu --no-sandbox --disable-dev-shm-usage --disable-extensions
        # Use the optimized headless test runner
        command: npm run test:e2e:batched
        # Limit CPU and memory usage
        deploy:
            resources:
                limits:
                    cpus: '4'
                    memory: 4G

volumes:
    cypress_node_modules:
