services:
    bunkbot-ts:
        build:
            context: .
            dockerfile: Dockerfile
            # Add build cache for faster rebuilds
            cache_from:
                - node:18-alpine
        container_name: bunkbot
        env_file:
            - .env
        command: npm run start
        volumes:
            - ./:/app:delegated
            - node_modules:/app/node_modules
        ports:
            - '3000:3000'
        # Hot reload optimization
        environment:
            - CHOKIDAR_USEPOLLING=true
            - NODE_ENV=development

volumes:
    node_modules:
