# Podman Compose for Production Deployment (Latest Images)
# ========================================================
# This file is designed for production deployment using the latest stable images.
# 
# Usage:
#   podman-compose -f podman-compose.latest.yml up -d
#
# Image Format: ghcr.io/andrewgari/{service}:latest
# 
# Prerequisites:
#   - Ensure all latest images are published to GHCR
#   - Configure environment variables in .env file
#   - Verify PostgreSQL credentials are set
#
# For production deployment, consider:
#   - Setting up proper SSL/TLS termination
#   - Configuring log aggregation
#   - Setting up monitoring and alerting
#   - Implementing backup strategies for PostgreSQL data

services:
  # PostgreSQL Database - Shared by services that need persistence
  postgres:
    image: postgres:15-alpine
    container_name: starbunk-postgres-latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-starbunk}
      POSTGRES_USER: ${POSTGRES_USER:-starbunk}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_latest_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d:ro
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-starbunk} -d ${POSTGRES_DB:-starbunk}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - starbunk-latest-network
    logging:
      driver: journald
      options:
        tag: "starbunk-postgres-latest"

  # BunkBot - Reply bots and admin commands (Latest Stable)
  bunkbot:
    image: ghcr.io/andrewgari/bunkbot:latest
    container_name: starbunk-bunkbot-latest
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - STARBUNK_TOKEN=${STARBUNK_TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - GUILD_ID=${GUILD_ID}
      - WEBHOOK_URL=${WEBHOOK_URL:-}
      - DATABASE_URL=${DATABASE_URL:-postgresql://${POSTGRES_USER:-starbunk}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-starbunk}}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - OPENAI_DEFAULT_MODEL=${OPENAI_DEFAULT_MODEL:-gpt-4o-mini}
      - DEBUG_MODE=${DEBUG_MODE:-false}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    ports:
      - "${BUNKBOT_PORT:-3000}:3000"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - starbunk-latest-network
    logging:
      driver: journald
      options:
        tag: "starbunk-bunkbot-latest"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # DJCova - Music service (Latest Stable)
  djcova:
    image: ghcr.io/andrewgari/djcova:latest
    container_name: starbunk-djcova-latest
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - STARBUNK_TOKEN=${STARBUNK_TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - GUILD_ID=${GUILD_ID}
      - DEBUG_MODE=${DEBUG_MODE:-false}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    ports:
      - "${DJCOVA_PORT:-3001}:3001"
    volumes:
      - djcova_latest_cache:/app/cache
      - djcova_latest_temp:/tmp
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3001/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - starbunk-latest-network
    logging:
      driver: journald
      options:
        tag: "starbunk-djcova-latest"
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # Starbunk-DND - D&D features and bridge (Latest Stable)
  starbunk-dnd:
    image: ghcr.io/andrewgari/starbunk-dnd:latest
    container_name: starbunk-dnd-latest
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - STARBUNK_TOKEN=${STARBUNK_TOKEN}
      - SNOWBUNK_TOKEN=${SNOWBUNK_TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - GUILD_ID=${GUILD_ID}
      - DATABASE_URL=${DATABASE_URL:-postgresql://${POSTGRES_USER:-starbunk}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-starbunk}}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_DEFAULT_MODEL=${OPENAI_DEFAULT_MODEL:-gpt-4o-mini}
      - OLLAMA_API_URL=${OLLAMA_API_URL:-}
      - OLLAMA_DEFAULT_MODEL=${OLLAMA_DEFAULT_MODEL:-}
      - DEBUG_MODE=${DEBUG_MODE:-false}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    ports:
      - "${STARBUNK_DND_PORT:-3002}:3002"
    volumes:
      - dnd_latest_data:/app/data
      - dnd_latest_campaigns:/app/data/campaigns
      - dnd_latest_context:/app/data/llm_context
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3002/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - starbunk-latest-network
    logging:
      driver: journald
      options:
        tag: "starbunk-dnd-latest"
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # CovaBot - AI personality bot (Latest Stable)
  covabot:
    image: ghcr.io/andrewgari/covabot:latest
    container_name: starbunk-covabot-latest
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - STARBUNK_TOKEN=${STARBUNK_TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - GUILD_ID=${GUILD_ID}
      - DATABASE_URL=${DATABASE_URL:-postgresql://${POSTGRES_USER:-starbunk}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-starbunk}}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_DEFAULT_MODEL=${OPENAI_DEFAULT_MODEL:-gpt-4o-mini}
      - DEBUG_MODE=${DEBUG_MODE:-false}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    ports:
      - "${COVABOT_PORT:-3003}:3003"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3003/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - starbunk-latest-network
    logging:
      driver: journald
      options:
        tag: "starbunk-covabot-latest"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

# Named volumes for persistent data (latest/production)
volumes:
  postgres_latest_data:
    driver: local
  djcova_latest_cache:
    driver: local
  djcova_latest_temp:
    driver: local
  dnd_latest_data:
    driver: local
  dnd_latest_campaigns:
    driver: local
  dnd_latest_context:
    driver: local

# Custom network for service communication (latest/production)
networks:
  starbunk-latest-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16
