global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alertmanager@starbunk.local'
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'service', 'instance']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'web.hook'
  routes:
    # Discord bot specific alerts
    - match:
        service: bunkbot
      receiver: discord-bunkbot
    - match:
        service: djcova
      receiver: discord-djcova
    - match:
        service: covabot
      receiver: discord-covabot
    - match:
        service: starbunk-dnd
      receiver: discord-starbunk-dnd
    # Critical system alerts
    - match_re:
        severity: critical|high
      receiver: critical-alerts
    # Default catch-all
    - receiver: 'web.hook'

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://127.0.0.1:5001/'

  - name: discord-bunkbot
    webhook_configs:
      - url: '{{ .ExternalURL }}/webhook/discord'
        send_resolved: true
        title: '[ALERT] BunkBot Service'
        text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'

  - name: discord-djcova
    webhook_configs:
      - url: '{{ .ExternalURL }}/webhook/discord'
        send_resolved: true
        title: '[ALERT] DJCova Music Service'
        text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'

  - name: discord-covabot
    webhook_configs:
      - url: '{{ .ExternalURL }}/webhook/discord'
        send_resolved: true
        title: '[ALERT] CovaBot AI Service'
        text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'

  - name: discord-starbunk-dnd
    webhook_configs:
      - url: '{{ .ExternalURL }}/webhook/discord'
        send_resolved: true
        title: '[ALERT] Starbunk D&D Service'
        text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'

  - name: critical-alerts
    webhook_configs:
      - url: '{{ .ExternalURL }}/webhook/discord'
        send_resolved: true
        title: '[CRITICAL] System Alert'
        text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']

templates:
  - '/etc/alertmanager/templates/*.tmpl'