server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://starbunk-loki:3100/loki/api/v1/push

scrape_configs:
  # Docker container logs
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*.log
    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            attrs:
      - json:
          expressions:
            tag:
          source: attrs
      - regex:
          expression: (?P<container_name>(?:[^|]){1,10})
          source: tag
      - timestamp:
          format: RFC3339Nano
          source: time
      - labels:
          stream:
          container_name:
      - output:
          source: output

  # Starbunk Discord Bot containers - specific log collection
  - job_name: starbunk-containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: starbunk-bots
          __path__: /var/lib/docker/containers/*/*.log
    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            attrs:
            time: time
      - json:
          expressions:
            tag:
          source: attrs
      # Extract container name from Docker tag
      - regex:
          expression: ^[^-]+-(?P<container_name>.+)$
          source: tag
      # Only process our containers
      - match:
          selector: '{container_name=~"starbunk-.*"}'
          stages:
            - labels:
                container_name:
                stream:
            - timestamp:
                format: RFC3339Nano
                source: time
            - output:
                source: output

  # System logs
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: syslog
          __path__: /var/log/syslog
    pipeline_stages:
      - match:
          selector: '{job="syslog"}'
          stages:
            - regex:
                expression: '^(?P<timestamp>\S+\s+\S+\s+\S+) (?P<hostname>\S+) (?P<service>\S+)(\[(?P<pid>\d+)\])?: (?P<message>.*)$'
            - labels:
                hostname:
                service:
            - timestamp:
                format: Jan 2 15:04:05
                source: timestamp