version: '3.8'

networks:
  covabot-network:
    driver: bridge

services:
  qdrant:
    image: qdrant/qdrant:v1.7.4
    container_name: qdrant-covabot
    networks:
      - covabot-network
    ports:
      - "6333:6333"
      - "6334:6334"  # gRPC (optional)
    volumes:
      - /mnt/user/appdata/qdrant/storage:/qdrant/storage
      - /mnt/user/appdata/qdrant/config:/qdrant/config
    environment:
      - QDRANT__CONFIG_PATH=/qdrant/config/production.yaml
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sh", "-c", "wget -qO- http://localhost:6333/ | grep -q qdrant || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  covabot:
    image: ghcr.io/andrewgari/covabot:latest
    container_name: covabot-production
    networks:
      - covabot-network
    depends_on:
      qdrant:
        condition: service_healthy
    env_file:
      - /mnt/user/appdata/covabot/.env.production
    volumes:
      - /mnt/user/appdata/covabot/data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "process.exit(0)"]
      interval: 60s
      timeout: 30s
      retries: 3

  # Optional: Qdrant Web UI for monitoring
  qdrant-ui:
    image: qdrant/qdrant-web-ui:latest
    container_name: qdrant-ui
    networks:
      - covabot-network
    ports:
      - "3000:3000"
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    depends_on:
      - qdrant
    restart: unless-stopped
    profiles:
      - monitoring  # Use --profile monitoring to enable
