name: Build Docker Image

on:
    workflow_call:
        inputs:
            tag:
                required: true
                type: string
            should_run:
                required: false
                type: boolean
                default: true

jobs:
    check-changes:
        runs-on: ubuntu-latest
        outputs:
            should-build: ${{ steps.filter.outputs.docker }}
        steps:
            - uses: actions/checkout@v3
            - uses: dorny/paths-filter@v2
              id: filter
              with:
                  filters: |
                      docker:
                        - 'src/**/*.ts'
                        - 'src/**/*.js'
                        - 'package.json'
                        - 'package-lock.json'
                        - 'Dockerfile'
                        - 'docker-compose*.yml'
                        - '.dockerignore'

    build:
        needs: check-changes
        if: ${{ inputs.should_run && needs.check-changes.outputs.should-build == 'true' }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Build Docker Image
              run: |
                  docker build -t my-app:${{ inputs.tag }} .
