name: Containers CI

on:
  pull_request:
  push:

jobs:
  changes:
    name: Detect changed areas
    runs-on: ubuntu-latest
    outputs:
      shared: ${{ steps.filter.outputs.shared }}
      covabot: ${{ steps.filter.outputs.covabot }}
      bunkbot: ${{ steps.filter.outputs.bunkbot }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Determine changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            shared:
              - 'containers/shared/**'
              - 'packages/shared/**'
            covabot:
              - 'containers/covabot/**'
            bunkbot:
              - 'containers/bunkbot/**'

  shared:
    name: Shared (tests)
    needs: changes
    if: needs.changes.outputs.shared == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install deps (shared)
        run: npm ci
        working-directory: containers/shared

      - name: Run tests (shared)
        run: npm test --silent
        working-directory: containers/shared

  covabot:
    name: CovaBot (tests + build)
    needs: changes
    if: needs.changes.outputs.covabot == 'true' || needs.changes.outputs.shared == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install deps (covabot)
        run: npm ci
        working-directory: containers/covabot

      - name: Run tests (covabot)
        run: npm test --silent
        working-directory: containers/covabot

      - name: Build (covabot)
        run: npm run build --silent
        working-directory: containers/covabot

  bunkbot:
    name: BunkBot (tests)
    needs: changes
    if: needs.changes.outputs.bunkbot == 'true' || needs.changes.outputs.shared == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install deps (bunkbot)
        run: npm ci
        working-directory: containers/bunkbot

      - name: Run tests (bunkbot)
        run: npm test --silent
        working-directory: containers/bunkbot

      # NOTE: Build step intentionally omitted for now to keep scope minimal
      # and avoid compiling test/refactor files. We can enable after tightening tsconfig.

