name: Create Snapshot Image

on:
    workflow_dispatch:
        inputs:
            snapshot_name:
                description: 'Snapshot identifier (e.g., beta1, rc1)'
                required: true
                type: string

jobs:
    build-snapshot:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Get version from package.json
              id: version
              run: |
                  echo "version=$(node -p "require('./package.json').version")" >> "$GITHUB_OUTPUT"

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and Push Snapshot Image
              uses: docker/build-push-action@v4
              with:
                  context: .
                  push: true
                  tags: |
                      ghcr.io/${{ github.repository }}:${{ steps.version.outputs.version }}-${{ inputs.snapshot_name }}
                      ghcr.io/${{ github.repository }}:snapshot-latest
