name: Destroy Docker Container

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Stop and Remove Docker Container
        run: |
          docker stop my-app-container-${{ inputs.tag }} || true
          docker rm my-app-container-${{ inputs.tag }} || true
