name: Destroy Docker Image Workflow

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

jobs:
  destroy-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Stop and Remove PR Container
        run: |
          docker stop my-app-container-pr-${{ inputs.tag }} || true
          docker rm my-app-container-pr-${{ inputs.tag }} || true
