name: Push commit
on: push
permissions:
  contents: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create report file
        run: date +%s > report.txt
      - name: Commit report
        run: |
          git config --global user.name 'Andrew Gari'
          git config --global user.email 'covadax.ag@gmail.com'
          git commit -am "Automated report"
          git push
          