name: PR Build Check

on:
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    check_changes:
        runs-on: ubuntu-latest
        outputs:
            non_test_changed: ${{ steps.filter.outputs.non_test }}
        steps:
            - uses: actions/checkout@v4
            - uses: dorny/paths-filter@v2
              id: filter
              with:
                  filters: |
                      non_test:
                          - 'src/**'
                          - '!src/tests/**'

    build:
        name: 🔨 Build
        needs: check_changes
        if: needs.check_changes.outputs.non_test_changed == 'true'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  cache: 'npm'

            - name: Install Dependencies
              run: npm ci

            - name: Build App
              run: npm run build
