name: PR Docker Test Workflow

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t my-app:${{ inputs.tag }} .

      - name: Run Docker Container
        run: |
          docker run -d --name my-app-container-${{ inputs.tag }} -p 8080:8080 my-app:${{ inputs.tag }}