name: PR Docker Test Workflow

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

jobs:
  test-pr-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: false
          tags: pr-${{ inputs.tag }}

      - name: Run Docker Container
        run: |
          docker run -d --name my-app-container-pr-${{ inputs.tag }} -p 8080:8080 my-app:pr-${{ inputs.tag }}
