name: PR Lint Check

on:
    pull_request:
        types: [opened, synchronize, reopened]
        paths:
            - '**.js'
            - '**.ts'
            - '**.jsx'
            - '**.tsx'
            - '.eslintrc*'
            - '.prettierrc*'
            - 'tsconfig.json'
            - '!**.md'
            - '!src/tests/fixtures/**'
            - '!**.test.ts'
            - '!**.test.js'

jobs:
    lint:
        name: 🔍 Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  cache: 'npm'

            - name: Install Dependencies
              run: npm ci

            - name: Run Lint
              run: npm run lint
