name: PR Merge Workflow

on:
  pull_request:
    types:
      - closed

jobs:
  destroy-pr-container:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/destroy-docker-image.yml
    with:
      tag: pr-${{ github.event.pull_request.number }}

  build-and-publish:
    if: github.event.pull_request.merged == true
    needs: destroy-pr-container
    uses: ./.github/workflows/publish-docker-image.yml
    with:
      tag: main
