name: PR Merge Workflow

on:
    pull_request:
        types:
            - closed
        paths:
            - 'src/**'
            - 'tests/**'
            - 'test/**'
            - 'package.json'
            - 'package-lock.json'
            - 'tsconfig.json'
            - 'jest.config.js'
            - '.eslintrc.json'
            - 'Dockerfile'
            - 'docker-compose*.yml'

jobs:
    check-changes:
        runs-on: ubuntu-latest
        outputs:
            should-run-docker: ${{ steps.filter.outputs.docker }}
        steps:
            - uses: actions/checkout@v3
            - uses: dorny/paths-filter@v2
              id: filter
              with:
                  filters: |
                      docker:
                        - 'src/**/*.ts'
                        - 'src/**/*.js'
                        - 'package.json'
                        - 'package-lock.json'
                        - 'Dockerfile'
                        - 'docker-compose*.yml'
                        - '.dockerignore'

    destroy-pr-container:
        if: github.event.pull_request.merged == true && (needs.check-changes.outputs.should-run-docker == 'true' || github.event_name == 'workflow_dispatch')
        needs: check-changes
        uses: ./.github/workflows/destroy-docker-image.yml
        with:
            tag: pr-${{ github.event.pull_request.number }}

    destroy-branch-container:
        if: github.event.pull_request.merged == true && (needs.check-changes.outputs.should-run-docker == 'true' || github.event_name == 'workflow_dispatch')
        needs: [check-changes, destroy-pr-container]
        uses: ./.github/workflows/destroy-docker-image.yml
        with:
            tag: ${{ github.event.pull_request.head.ref }}

    publish:
        if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' && (needs.check-changes.outputs.should-run-docker == 'true' || github.event_name == 'workflow_dispatch')
        needs: [check-changes, destroy-branch-container]
        uses: ./.github/workflows/publish-docker-image.yml
        with:
            tag: latest
