name: PR Merge Workflow

on:
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Delete PR Docker image
        uses: actions/delete-package-versions@v4
        with:
          owner: ${{ github.repository_owner }}
          package-name: ${{ github.event.repository.name }}
          package-type: container
          version-pattern: pr-${{ github.event.pull_request.number }}
          
  release:
    if: github.event.pull_request.merged == true
    needs: cleanup
    uses: ./.github/workflows/publish-docker-image.yml
    with:
      tag: main
    secrets:
      GHCR_PAT: ${{ secrets.GHCR_PAT }}