name: PR Check Workflow

on:
    pull_request:
        types: [opened, synchronize]
        paths:
            - 'src/**'
            - 'tests/**'
            - 'test/**'
            - 'package.json'
            - 'package-lock.json'
            - 'tsconfig.json'
            - 'jest.config.js'
            - '.eslintrc.json'
            - 'Dockerfile'
            - 'docker-compose*.yml'
    workflow_dispatch: # Allow manual trigger

jobs:
    check-changes:
        runs-on: ubuntu-latest
        outputs:
            should-run-tests: ${{ steps.filter.outputs.tests }}
            should-run-build: ${{ steps.filter.outputs.build }}
            should-run-docker: ${{ steps.filter.outputs.docker }}
        steps:
            - uses: actions/checkout@v3
            - uses: dorny/paths-filter@v2
              id: filter
              with:
                  filters: |
                      tests:
                          - 'src/**/*.ts'
                          - 'src/**/*.js'
                          - 'test/**/*.ts'
                          - 'test/**/*.js'
                          - 'tests/**/*.ts'
                          - 'tests/**/*.js'
                          - 'package.json'
                          - 'package-lock.json'
                          - 'jest.config.js'
                          - 'tsconfig.json'
                      build:
                          - 'src/**/*.ts'
                          - 'src/**/*.js'
                          - 'package.json'
                          - 'package-lock.json'
                          - 'tsconfig.json'
                          - '.eslintrc.json'
                      docker:
                          - 'src/**/*.ts'
                          - 'src/**/*.js'
                          - 'package.json'
                          - 'package-lock.json'
                          - 'Dockerfile'
                          - 'docker-compose*.yml'
                          - '.dockerignore'

    unit-tests:
        name: Unit Tests
        needs: check-changes
        if: ${{ needs.check-changes.outputs.should-run-tests == 'true' || github.event_name == 'workflow_dispatch' }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '18'

            - name: Install Dependencies
              run: npm ci

            - name: Run Tests
              run: npm test

    verify:
        runs-on: ubuntu-latest
        needs: [check-changes, unit-tests]
        if: ${{ needs.check-changes.outputs.should-run-build == 'true' || github.event_name == 'workflow_dispatch' }}
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '18'

            - name: Install Dependencies
              run: npm ci

            - name: Lint Check
              run: npm run lint

            - name: Build Check
              run: npm run build

            - name: Start Check
              run: |
                  npm start & sleep 10
                  kill $!

    docker-check:
        runs-on: ubuntu-latest
        needs: [check-changes, verify]
        if: ${{ needs.check-changes.outputs.should-run-docker == 'true' || github.event_name == 'workflow_dispatch' }}
        steps:
            - uses: actions/checkout@v4

            - name: Build Docker Image
              env:
                  PR_NUMBER: ${{ github.event.pull_request.number }}
              run: |
                  docker build -t ghcr.io/${{ github.repository }}:pr-$PR_NUMBER .
