name: PR Branch Update Workflow

on:
  push:
    branches:
      - 'pr-*'

jobs:
  destroy-old-container:
    uses: ./.github/workflows/destroy-docker-image.yml
    with:
      tag: ${{ github.ref_name }}

  build-and-start:
    needs: destroy-old-container
    uses: ./.github/workflows/pr-docker-test.yml
    with:
      tag: ${{ github.ref_name }}