name: PR Update Workflow

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Use Reusable Workflow for PR Test
        uses: ./.github/workflows/pr-docker-test.yml
        with:
          tag: pr-${{ github.event.pull_request.number }}
