name: PR Check Workflow

on:
    pull_request:
        types: [opened, synchronize]

jobs:
    unit-tests:
        name: Unit Tests
        uses: ./.github/workflows/unit-tests.yml

    verify:
        runs-on: ubuntu-latest
        needs: unit-tests
        steps:
            - uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'

            - name: Install Dependencies
              run: npm ci

            - name: Lint Check
              run: npm run lint

            - name: Build Check
              run: npm run build

            - name: Start Check
              run: |
                  npm start & sleep 10
                  kill $!

            - name: Build and Push Docker Image
              env:
                  PR_NUMBER: ${{ github.event.pull_request.number }}
              run: |
                  docker build -t ghcr.io/${{ github.repository }}:pr-$PR_NUMBER .
                  docker push ghcr.io/${{ github.repository }}:pr-$PR_NUMBER
