name: Publish snowbunk on main

on:
  push:
    branches: [ main ]
    paths:
      - 'containers/snowbunk/**'
      - 'containers/shared/**'
      - '.github/workflows/**'
      - '.github/path-filters.yml'
      - 'Dockerfile*'
      - 'docker/docker-compose*.yml'
      - 'docker/podman-compose*.yml'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
      - 'docker/.dockerignore'

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/snowbunk

jobs:
  publish-snowbunk:
    name: Publish snowbunk image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}

      - name: Build and push snowbunk
        uses: docker/build-push-action@v5
        with:
          context: .
          file: containers/snowbunk/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: |
            type=gha,scope=snowbunk
          cache-to: |
            type=gha,mode=max,scope=snowbunk
          platforms: linux/amd64

