name: Publish Docker Image

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:${{ inputs.tag }} .
          docker push ghcr.io/${{ github.repository }}:${{ inputs.tag }}
