name: Build and Publish Docker Image

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
    secrets:
      GHCR_PAT:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/starbunk-js:${{ inputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Tag latest if main
        if: inputs.tag == 'main'
        run: |
          docker tag ghcr.io/${{ github.repository_owner }}/starbunk-js:${{ inputs.tag }} ghcr.io/${{ github.repository_owner }}/starbunk-js:latest
          docker push ghcr.io/${{ github.repository_owner }}/starbunk-js:latest

      - name: Verify repository and package permissions
        run: |
          echo "Checking permissions for GHCR"
          curl -u "${{ github.actor }}:${{ secrets.GHCR_PAT }}" -X GET "https://ghcr.io/v2/${{ github.repository_owner }}/starbunk-js/tags/list"
