name: Setup Environment

on:
    workflow_call:
        outputs:
            cache-hit:
                description: 'Whether the npm cache was hit'
                value: ${{ jobs.setup.outputs.cache-hit }}

jobs:
    setup:
        runs-on: ubuntu-latest
        outputs:
            cache-hit: ${{ steps.npm-cache.outputs.cache-hit }}
        steps:
            - name: 📥 Checkout code
              uses: actions/checkout@v4

            - name: 🔧 Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '18'
                  cache: 'npm'

            - name: 📦 Install Dependencies
              id: npm-cache
              run: |
                  echo "::group::Installing dependencies"
                  npm ci
                  echo "::endgroup::"
                  echo "✅ Dependencies installed successfully"
